### ISSUE TITLE
Use ES Modules for Cloudflare (Node.js) guide?

### ISSUE THREAD

**Issue by nelsonjchen** [grammyjs/website#1049]
ES Modules are the preferred format for Cloudflare Workers. 

Additionally, ES Modules are required for certain new functionality or services in Cloudflare Workers:

https://developers.cloudflare.com/workers/reference/migrate-to-module-workers/#advantages-of-migrating

It looks like the Deno guide already uses ES Modules.

https://developers.cloudflare.com/workers/get-started/guide/

**Comment by KnorpelSenf** [comment]
We're only waiting for @habemuscode to translate #1043 and then this should be fixed
