### ISSUE TITLE
Spanish translation tracking

### ISSUE THREAD

**Issue by habemuscode** [grammyjs/website#135]
# English

## Description

- This issue is for tracking the translation progress of all pages.
- This issue will be closed when the documentation is finished.

## I want to collaborate

1. Being a translator

- Read [how to contribute in translations](https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md#translations)
- Translate with your native-speaker level, **DO NOT** just copy the section to some translator tool and paste back the result
- Take one untranslated page, translate and create PR from your fork to the main project. One PR for page, to better split in parallel the work and less tired reviews

2. Being a reviewer

- Find the PR's created for translations and review them. Add all notes that you consider.

## Note

Words related to methods, function names, variables... mustn't be translated. Here are some examples:
- bot
- update
- keyboard / inline keyboard
- webhook
- payload
- ... (feel free to add more, but make sense)

---

# Español

## Descripción

- Esta issue es para rastrear el progreso de traducción de todas las páginas.
- Está issue será cerrada cuando la documentación este completada.

## Me gustaría colaborar

1. Como traductor

- Leéte [como contribuir en las traducciones](https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md#translations)
- Traduce con tu nivel nativo, **NO** simplemente copies el contenido en una herramienta de traducción y pegues el resultado
- Escoge una página no traducida, traducela y crea un PR desde el fork del projecto al projecto principal. Un PR por página, para favorecer la parallelización del trabajo y reducir el cansancio de la revisión.

2. Como validador

- Encuentra un PR creado de traducciones y revisalo. Añade todos los comentarios que consideres.

## Nota

Palabras relativas a métodos, nombres de funciones, variables... no se traducen. Aquí algunos ejemplos:

- bot
- update
- keyboard / inline keyboard
- webhook
- payload
- ... (añade más si consideras, pero con sentido común)

---

## Readme

- [README.md](https://github.com/grammyjs/website/blob/main/site/docs/es/README.md) -> #319

## Advanced

- [deployment.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/deployment.md) -> #293 
- [flood.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/flood.md) -> #294 
- [middleware.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/middleware.md) -> #295 
- [proxy.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/proxy.md) -> #296
- [README.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/README.md) -> #297
- [reliability.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/reliability.md) -> #298
- [scaling.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/scaling.md) -> #299
- [structuring.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/structuring.md) -> #300
- [transformers.md](https://github.com/grammyjs/website/blob/main/site/docs/es/advanced/transformers.md) -> #301

## Demo

- [examples.md](https://github.com/grammyjs/website/blob/main/site/docs/es/demo/examples.md) -> #302
- [README.md](https://github.com/grammyjs/website/blob/main/site/docs/es/demo/README.md) -> #310

## Guide

- [api.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/api.md) -> #303
- [basics.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/basics.md) -> #304
- [commands.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/commands.md) -> #305 
- [context.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/context.md) -> #306
- [deployment-types.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/deployment-types.md) -> #307
- [errors.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/errors.md) -> #308
- [files.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/files.md) -> #309
- [filter-queries.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/filter-queries.md) ->  #311
- [games.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/games.md) -> #312
- [getting-started.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/getting-started.md) -> #313
- [inline-queries.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/inline-queries.md) -> #314
- [introduction.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/introduction.md) -> #211 
- [middleware.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/middleware.md)
    -> #212
    -> #335
- [README.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/README.md) -> #318 

## Hosting

- [deno-deploy.md](https://github.com/grammyjs/website/blob/main/site/docs/es/hosting/deno-deploy.md)
    -> #231 
    -> #357
- [gcf.md](https://github.com/grammyjs/website/blob/main/site/docs/es/hosting/gcf.md) -> #232 
- [heroku.md](https://github.com/grammyjs/website/blob/main/site/docs/es/hosting/heroku.md) -> #235 
- [vps.md](https://github.com/grammyjs/website/blob/main/site/docs/es/hosting/vps.md) -> #344

## Plugins

- [auto-retry.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/auto-retry.md) -> #236 
- [command-filter.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/command-filter.md) -> #237 
- [console-time.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/console-time.md) -> #238 
- [files.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/files.md) -> #239 
- [hydratate.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/hydratate.md) -> #240 
- [i18n.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/i18n.md) -> #244 
- [keyboard.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/keyboard.md) -> #253
- [menu.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/menu.md) -> #254 
- [parse-mode.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/parse-mode.md) -> #255
- [ratelimiter.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/ratelimiter.md)
    -> #256
    -> #356
- [README.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/README.md) -> #257
- [router.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/router.md) -> #258
- [runner.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/runner.md) -> #259
- [session.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/session.md) -> #260
- [stateless-question.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/stateless-question.md) -> #261
- [transformer-throttler.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/transformer-throttler.md) -> #262
- [emoji.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/emoji.md) -> #345
- [fluent.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/fluent.md) -> #346
- [guide.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/guide.md) -> #347
- [middlewares.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/middlewares.md) -> #349

## Resources

- [comparison.md](https://github.com/grammyjs/website/blob/main/site/docs/es/resources/comparison.md) -> #263
- [faq.md](https://github.com/grammyjs/website/blob/main/site/docs/es/resources/faq.md) -> #264
- [about.md](https://github.com/grammyjs/website/blob/main/site/docs/es/resources/about.md) -> #343

**Comment by KnorpelSenf** [comment]
I will have to buy more build minutes on Netlify if every change to the site causes three articles to be updated. Or maybe we can trigger deploy previews manually, I will investigate this. cc @WingLim

**Comment by KnorpelSenf** [comment]
See #135

**Comment by rojserbest** [comment]
> See #142

UwU ✨

**Comment by roj1512** [comment]
Wouldn’t it be better if the tasks were like

```
- [ ] #141 
- [ ] #142
```

**Comment by roj1512** [comment]
I mean doing that for the open PRs only.

**Comment by KnorpelSenf** [comment]
@habemuscode it's sad to see the translations stalling :(

You put a lot of effort into this, I'm surprised that no one is volunteering to review your work. It's slowly getting out of sync, I'm not sure if anyone still has an overview over which things are up to date.

@habemuscode @roj1512 what's your take on how we should proceed from here so that we don't eventually need to close all PQs unmerged?

**Comment by roj1512** [comment]
@habemuscode Let’s give him some time (max 5 days) to respond to [this](https://github.com/grammyjs/website/issues/135#issuecomment-1099633682).

**Comment by roj1512** [comment]
@KnorpelSenf Let’s give him some time (max 5 days) to respond to [this](https://github.com/grammyjs/website/issues/135#issuecomment-1099633682).

**Comment by roj1512** [comment]
@habemuscode We’re unhappy to know the fact that you have left us for a while now.

We’ve decided to close the Spanish translation PRs, along with this tracker.

We would also like you to know that this action does not mean that all your efforts will be gone. It is more of a recognition of the inactievness of the Spanish translation process.

None of your branches will be touched, either, so they can be used again, reviewed, or at least taken as a reference if the process started again someday.

**Comment by roj1512** [comment]
@habemuscode https://github.com/grammyjs/website/blob/feat/spanish-translations/site/docs/es/guide/middleware.md is outdated, too. It is missing some examples.

**Comment by habemuscode** [comment]
@roj1512 New PR for `es/guide/middleware` added created, updated and added here to be tracked.

**Comment by roj1512** [comment]
@habemuscode Do you think you should have the headings (#) in Title Case?

**Comment by roj1512** [comment]
@habemuscode Here are the new pages, in case you need them:

- resources
	- resources/about.md
- hosting
	- hosting/vps.md
- plugins
	  - plugins/emoji.md
	  - plugins/fluent.md
	  - plugins/guide.md
	  - plugins/middlewares.md

**Comment by habemuscode** [comment]
> @habemuscode Here are the new pages, in case you need them:
> 
>     * resources
>       
>       * resources/about.md
> 
>     * hosting
>       
>       * hosting/vps.md
> 
>     * plugins
>       
>       * plugins/emoji.md
>       * plugins/fluent.md
>       * plugins/guide.md
>       * plugins/middlewares.md

Thanks, created new PRs!

**Comment by habemuscode** [comment]
> Is there a pull request to translate the navigation bar yet?

Nope, that things included config, etc. will be after pushed in the PR of `feat/spanish-translations`, so we can check everything works. At least, is my plan, but tell me suggestions :)

**Comment by roj1512** [comment]
How do you check if everything works if there is not a good way to navigate?

**Comment by KnorpelSenf** [comment]
@habemuscode I created #351 so that it will be easier for you to configure things correctly. Now you can focus on the actual translations, rather than the configuration file format.

**Comment by CikiMomogi** [comment]
A little suggestion to add the following key [selectLanguageText](https://github.com/grammyjs/website/blob/9d8b017e8ebd2ec77a4a9a684efe42e355a4bcc4/site/docs/.vuepress/config.ts#L716) to Spanish.

**Comment by CikiMomogi** [comment]
A little suggestion to add the following key to Spanish. https://github.com/grammyjs/website/blob/9d8b017e8ebd2ec77a4a9a684efe42e355a4bcc4/site/docs/.vuepress/config.ts#L716

**Comment by KnorpelSenf** [comment]
Good idea! /cc @habemuscode

**Comment by CikiMomogi** [comment]
I discovered most of the anchor links are broken on the Spanish pages. I think we should review all the pages once again.
