### ISSUE TITLE
docs: zh/hosting/deno-deploy 

### ISSUE THREAD

**Issue by habemuscode** [grammyjs/website#136]
## English Version

[deno-deploy.md](https://github.com/grammyjs/website/blob/main/site/docs/hosting/deno-deploy.md)

cc @linbuxiao @WingLim @JiquanWang99

**Comment by KnorpelSenf** [comment]
Also see https://github.com/grammyjs/website/pull/129#issuecomment-986890094

**Comment by KnorpelSenf** [comment]
Closed in #140
