### ISSUE TITLE
Grammy Docs Bot should have an independent repository

### ISSUE THREAD

**Issue by habemuscode** [grammyjs/website#137]
## Description

As any other plugin or bot, Grammy Docs Bot should be outside of website repository. This repository is only for the website that preserve the documentation.

**Comment by KnorpelSenf** [comment]
That's true, we were just lazy. Moving the bot means having to change some config about the automatic deployment, but this is doable and I'll fix it when I have time :)

**Comment by KnorpelSenf** [comment]
Check out https://github.com/grammyjs/docs-bot
