### ISSUE TITLE
feat: How to set up a local Bot API server

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/website#154]
We have an example bot on how to set up a local Bot API server in the repo, but we don't yet have a document that really explains how to do it. Could be in the docs, could be in the README in the other repo—this needs to be decided.

**Comment by EdJoPaTo** [comment]
We should make sure to not explain too much about the bot server itself and only refer to its documentation (or provide improvements to it on their side). Running it can be done in many different ways while the way grammY connects to it is relatively straight forward.

**Comment by KnorpelSenf** [comment]
I agree.

**Comment by KnorpelSenf** [comment]
You are very right! 🎉
