### ISSUE TITLE
feat: Interactive filter query explorer

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/website#158]
Paste your filter query, and get visualised what it means, and what kinds of updates would be caught. Not sure how much effort this is. Ideally, we don't have to manually keep this in sync with the code.

We might have to drop this if it is too much work. After all, filter queries are not _that_ hard to understand, so it might not justify the effort.

**Comment by roj1512** [comment]
Now available at https://tools.grammy.dev/filter-query-browser.
