### ISSUE TITLE
feat: VSCode extension

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/website#159]
We may want to have some sort of integration between the docs and the code editor in order to bring even better documentation into the workflow. This is a very hard task (unless someone shows up who has prior experience in creating VSCode extensions) but it may be pretty outstanding in the development experience.

As a starting point, we may want to bundle up the logic of #158 into the extension and display it when the user hovers the cursor over a filter query.

**Comment by code-withAshish** [comment]
I was wondering about the implementation of the extension if it was to be made as grammy is written primarily in typescript which provides a robust IDE support and autocompletion out of the box.
So what exactly do we mean when we say 


> We may want to have some sort of integration between the docs and the code editor in order to bring even better documentation into the workflow.

**Comment by KnorpelSenf** [comment]
Further things will be tracked in https://github.com/grammyjs/vscode.
