### ISSUE TITLE
Add warning about build() to keyboard plugin

### ISSUE THREAD

**Issue by Loskir** [grammyjs/website#473]
Something like "In the past it was required to use `.build()` to add properties like `resize_keyboard`. Now they are supported out of the box and you shouldn't use `.build()`. Note that if you use build, properties set with `.resized()` won't be applied"

Must have an anchor link so we can use it in the code

**Comment by Loskir** [comment]
not relevant anymore? https://github.com/grammyjs/grammY/pull/259

**Comment by KnorpelSenf** [comment]
Correct.
