### ISSUE TITLE
feat: migrate vuepress to vuepress-vite or vitepress

### ISSUE THREAD

**Issue by WingLim** [grammyjs/website#49]
`vuepress` is using webpack which is much slower than `vuepress-vite` or `vitepress`(they are using vite and esbuild).

I have tested the build time between `vuepress` and `vuepress-vite`, here is the result:

```
+---------+----------+---------------+
|         | vuerepss | vuepress-vite |
+---------+----------+---------------+
| Time1   | 30.29s   | 17.77s        |
| Time2   | 29.67s   | 16.87s        |
| Average | 29.98s   | 17.32s        |
+---------+----------+---------------+
```

`vuepress-vite` is **40%** faster than `vuepress` in my `i5-9500` computer.

Migrate to `vuepress-vite` is very simple and easy, or we can migrate to `vitepress`(to vitepress is a bit complicated, but I will do the job).

There will be a PR migrate to `vuepress-vite`, you can take a look about it.

**Comment by linbuxiao** [comment]
@KnorpelSenf You might want to take a look at this.

**Comment by KnorpelSenf** [comment]
I tried this more than halt a year ago without success. I think there were some bugs at that point, not sure. Thanks for taking the initiative again!

I haven't looked into `vitepress` since then, but my last information is that `vitepress` is still lacking some features that we'd like to have. I still prefer `vuepress-vite`, so I'd go with that, unless you can convince me otherwise.

**Comment by WingLim** [comment]
> I tried this more than halt a year ago without success. 

Do you mean this bug? https://github.com/vuepress/vuepress-next/issues/176

I meat this bug yesterday when doing the migraion, delete the `node_modules` and `package-lock.json` then reinstall then work perfectly.

And yes, `vitepress` still lacking some features, that's why I am asking your option.

**Comment by KnorpelSenf** [comment]
> Do you mean this bug? [vuepress/vuepress-next#176](https://github.com/vuepress/vuepress-next/issues/176)

That one I managed to fix by reinstalling the dependencies, too. I believe there was something else, but I don't really remember tbh. I concluded by attempt with the mental note to migrate in a few months—so now is the time to do it.
