### ISSUE TITLE
Update info on Heroku in Hosting Comparison

### ISSUE THREAD

**Issue by Loskir** [grammyjs/website#508]
https://blog.heroku.com/next-chapter

There will be no free tier at all, it seems

**Comment by roj1512** [comment]
Did their thing take place?

**Comment by KnorpelSenf** [comment]
How should the info be updated?

**Comment by Loskir** [comment]
https://blog.heroku.com/next-chapter

There will be no free tier at all, it seems

**Comment by Loskir** [comment]
Minimum price will be $7/mo for 512MB RAM

**Comment by KnorpelSenf** [comment]
Thanks, I updated the description of this issue
