### ISSUE TITLE
Chinese translation tracking

### ISSUE THREAD

**Issue by WingLim** [grammyjs/website#55]
This issue is tracking for translating Chinese documentation.

For someone who want to join to translate documentation to Chinese, you can take a look in this issue, find out the untranslated section.

This issue will be closed when the documentation is largely translated.

There are more detail about translation in [CONTRIBUTING](https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md#translations), please read it first!

Here are some of the formats we are following:

**First and the most important:**
**DO NOT** just copy the section to google translator or something like that and paste back the result

**Second, obey this copywriting guidelines:**
[chinese-copywriting-guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)

**Third, some words we are not going to translate:**
- bot
- update
- keyboard / inline keyboard
- webhook
- payload
- ...(feel free to add more, but make sense)

---

这是用来追踪中文文档翻译情况的 issue。

如果你想参与进来翻译中文文档，你可以在这个 issue 里查看我们还未翻译的部分。

这个 issue 将会在文档基本上被翻译完成后关闭。

请先在 [CONTRIBUTING](https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md#translations) 查看更多关于贡献翻译的细节！

以下是我们正在遵守的一些规范：

**第一，也是最重要的：**
**不要**直接使用翻译软件翻译文档

**第二，遵守下列排版规则：**
[中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)

**第三，这里有一些我们不打算翻译并且保留的词组：**
- bot
- update
- keyboard / inline keyboard
- webhook
- payload
- ...（你可以添加更多我们不该翻译的词组）

**Comment by WingLim** [comment]
## advanced

**Comment by WingLim** [comment]
## demo

**Comment by WingLim** [comment]
## guide

**Comment by WingLim** [comment]
## hosting

**Comment by WingLim** [comment]
## plugins

**Comment by WingLim** [comment]
## resources

**Comment by rojserbest** [comment]
Also, review #54.

**Comment by WingLim** [comment]
> You can use a task list for the untranslated parts.

Yes, I am doing it.

**Comment by WingLim** [comment]
CC @linbuxiao

**Comment by KnorpelSenf** [comment]
I created a contribution guide. It explains more about how things should be translated. @WingLim could you mention in the issue that it exists, and link to it?

**Comment by WingLim** [comment]
> I created a contribution guide. It explains more about how things should be translated. @WingLim could you mention in the issue that it exists, and link to it?

Sure :-)

**Comment by linbuxiao** [comment]
nice!

**Comment by KnorpelSenf** [comment]
Thank you so much! That was a lot of effort you put into this. Excellent work, all of you guys :)
