### ISSUE TITLE
Improving the guide to hosting bots on VPS

### ISSUE THREAD

**Issue by niusia-ua** [grammyjs/website#770]
The current guide only explains how to keep the bot running continuously, leaving out other aspects such as the actual server rental, SSH settings, deployments, security issues, etc.

I have considerable experience in these matters, so I decided to contribute to the development of grammY documentation.

My goal is to describe the entire path of deploying the bot on a VPS, taking into consideration both a long polling and webhooks, namely:

1. Renting a server and a domain for the webhook. In the guide, I will use Hostinger as an example because of its rich documentation, multilingualism, and the best rates in terms of [quality, resources]:price.
2. Setting up the server control panel. For this, I will use Fastpanel because I know it well, and it has good documentation, a nice looking interface, is easy to customize, and is generally free.
3. Actually writing deployment scripts for GitHub and GitLab.
4. Support for bot work  (systemd or pm2).

I think that the new guide will be very useful for beginners, who will save their time, which they would otherwise spend on learning all these aspects on their own.

Soon I will create a PR draft where I will develop a new manual. I will write it in Ukrainian first, then translate it into English, and then submit it for review.

P.S. @KnorpelSenf supported my idea.

**Comment by roj1512** [comment]
I love this! I also admit that the guide is so raw and non-tasty as it is now.

**Comment by Nazar-Ant** [comment]
@roj1512 Can I ask you not to delete the `uk` branch after the merger with `main`? I definitely won't have time to write the article before the merger, so there may be problems if the `uk` branch is deleted.
