### ISSUE TITLE
Fix images for IV

### ISSUE THREAD

**Issue by dcdunkan** [grammyjs/website#867]
Some .webp images have .jpeg and some have .png replacements for IV. For IV of pages with images to be fixed, we need either all replacements to be PNG or JPEG. IV rules can't selectively replace some WEBPs with JPEG and some with PNG.

**Comment by KnorpelSenf** [comment]
Let's go PNG all the way then. We tend to serve screenshots and other graphics with large areas of the same colour, so it will produce several times smaller assets.
