### ISSUE TITLE
Reactions documentation: Please add information about enabling them in "allowed_updates" field.

### ISSUE THREAD

**Issue by coolk8** [grammyjs/website#990]
[https://grammy.dev/guide/reactions](https://grammy.dev/guide/reactions)

It would be helpful to mention that you need to enable these updates in the `bot.start` function, like this:
```
bot.start({
  allowed_updates: ["message", "message_reaction", "message_reaction_count"]
});
```
Otherwise, they wouldn't work.

Thank you anyway for the awesome library and your website!

**Comment by KnorpelSenf** [comment]
Good idea. Please check out #991. Does that explain it well enough?

**Comment by coolk8** [comment]
I think so. Thank you for quick reply and update!

> Good idea. Please check out #991. Does that explain it well enough?
